### PR TITLE
TRITON-2304 New image server names

### PR DESCRIPTION
**Pull request by bahamat**

### CODE REVIEW

**Comment by danmcd** [comment]
Before this change, was it "make test" fit?  If so, is it AFTER this change?

**Review by danmcd — DISMISSED** [review]

**Comment by bahamat** [comment]
Ok, I've spent *extensive* time on this.

* This repo was forked out of smartos-live to support Linux CN.
* To build this in a way that you can actually run the tests you need to either:
    * build on 18.4.0, copy to a GZ
    * build on Linux CN
* On SmartOS, all tests pass except `IMG.quickGetImage` and `IMG.quickGetImage err` due to a pre-existing callback race. Examining the tests themselves, if we actually ever won the race (which is basically impossible) the test would pass.
* The same tests pass before and after these changes.
* There's a companion change in TritonDataCenter/smartos-live#1047 where the tests can be run on the live platform.
* The tests that fail here, pass on the live platform, which is probably because on the PI we're using node v0.10, which can behave drastically different.

**Comment by danmcd** [comment]
Does seem that way...

**Review by danmcd — APPROVED** [review]
Since 2304 is a giant omnibus bug, your test notes here are sufficient.

**Pull request merged**
